r-prof/winch

.Rbuildignore
.github/workflows/example.yaml
.gitignore
R/add_trace_back.R
configure
src/Makevars
src/Makevars.in
src/configure.bash
src/trace_back.c

Test on macOS

---

DESCRIPTION
R/add_trace_back.R

Use path_is_libr()

---

.github/workflows/R-CMD-check.yaml

R CMD check workflow

---

DESCRIPTION

Bump dependency

---

R/zzz.R
src/init.c
src/trace_back_backtrace.c

init_library()

---

src/trace_back_backtrace.c

to work around missing debug info.

Use backtrace_simple()

---

.github/workflows/example.yaml

Use R from master

---

src/Makevars.in

Add Makefile rule

---

.github/workflows/R-CMD-check.yaml
.github/workflows/example.yaml
R/stop.R
R/zzz.R
src/Makevars.win
src/trace_back_backtrace.c
src/vendor/libbacktrace/backtrace.c
src/vendor/libbacktrace/simple.c
tests/testthat/test-stop.R
winch.Rproj

Windows support

---

DESCRIPTION

Add sysreq

---

R/add_trace_back.R
src/Makevars.win

i386 doesn't work

---

.Rbuildignore
CODE_OF_CONDUCT.md
README.Rmd
README.md

README with downlit

---

R/trace_back.R
man/winch_trace_back.Rd
vignettes/report.Rmd

Fix Solaris errors

---

README.Rmd
vignettes/report.Rmd

@krlmlr Here is a first copy edit of the winch documentation. It may be that this is so far outside my experience I can't see what might be missing, or your initial draft was pretty good. What was there just needed tweaks here and there. Again, possibly my lack of experience, but would a clearer example of using winch in practice be useful/doable?

Copy edit completed

---

configure
configure.win
src/Makevars.configure
src/Makevars.configure.win
src/Makevars.in
src/Makevars.win
src/configure.bash
src/configure.sh
src/configure.win.sh
src/trace_back_backtrace.c
tests/testthat/test-add_trace_back.R

to fix windows-oldrelease build.

Work around problems with spaces in PATH

---

DESCRIPTION
NEWS.md
cran-comments.md
src/Makevars.win
src/configure.sh
src/trace_back_unwind.c

CRAN release v0.0.2

---

NEWS.md
cran-comments.md

CRAN release v0.0.3

---

NEWS.md
cran-comments.md

CRAN release v0.0.4

---

.github/workflows/R-CMD-check.yaml
DESCRIPTION
src/trace_back.c
tests/example2.R
tests/example3.R
tests/example4.R
tests/example5.R
tests/example6.R
tests/example7.R
tests/example8.R

Simulate CRAN solaris

---

R/available.R

to avoid checks of third-party library.

Detect valgrind

---

tests/testthat/test-add_trace_back.R

Enable tests on CRAN

---

src/configure.win.sh
tests/testthat/test-stop.R

Work around CRAN failures

---

DESCRIPTION
NEWS.md
cran-comments.md

CRAN release v0.0.6

---

NEWS.md
cran-comments.md
src/trace_back_backtrace.c

CRAN release v0.0.8

---

NEWS.md
cran-comments.md

CRAN release v0.0.9

---

NEWS.md
cran-comments.md
vignettes/report.Rmd

CRAN release v0.0.10

---

NEWS.md
cran-comments.md

CRAN release v0.0.11

---

.Rbuildignore
NEWS.md
README.Rmd
README.md
cran-comments.md
src/vendor/libbacktrace/.editorconfig
src/vendor/libbacktrace/.github/workflows/check.yaml
src/vendor/libbacktrace/pecoff.c

CRAN release v0.0.12

---

NEWS.md
cran-comments.md

CRAN release v0.1.0
